### ISSUE TITLE
PyPi PodSixNet package for python 3

### ISSUE THREAD

**Issue by BohdanBorkivskyi** [chr15m/PodSixNet#16]
Could you please add this version to PyPi, for example with the package name PodSixNet3, so that it can be easily installed via pip ?

**Comment by BohdanBorkivskyi** [comment]
@chr15m yes, branch ```python3```. Well, I made a few simple games using PodSixNet3 and they worked good

**Comment by chr15m** [comment]
@BohdanBorkivskyi version 0.10.0 is up now and it should work on both Python 2 & 3.
