### ISSUE TITLE
Disconnecting From Server when wifi is down due to screen lock or sleep. 

### ISSUE THREAD

**Issue by salamohamad** [chr15m/PodSixNet#17]
First, I just want to say big thanks for this aiming piece of art. truly helpful and useful. 
I have a made a game using Pythonista for iOS and the game works perfectly but whenever I put the phone to sleep, the connection gets lost with the Server because most iPhones drop wifi while they are asleep. is there a way to have that connection hang until I am back online next time or there is no way around. 
where is the built in function _disconnected which clients received? 
Thank you and I hope it makes sense.

**Comment by salamohamad** [comment]
I found the solution! thank you

**Comment by chr15m** [comment]
@salamohamad great! What was the solution?

**Comment by salamohamad** [comment]
if the player has just started the app, they will be given a unique identifier and put together with another player to play. if the connection drops from either players we set a boolean to True and whenever the wifi comes back on we connect them again to the server and send the server a message to put this new channel in the the same game it was before  rather than putting it in a new game and we use that identifier to decide which game the player was playing before it was disconnected. it worked like a charm :). now after the wifi drops from the iPhone every time I am back in the game its like it ever disconnected. 
Thank you Chris for this wonderful tool.

**Comment by chr15m** [comment]
@salamohamad thanks. Good to have your solution here in case somebody faces the same issue in future. :+1:
