### ISSUE TITLE
async leads to invalid syntax with python 3.7.0

### ISSUE THREAD

**Issue by CydNoxzed** [chr15m/PodSixNet#19]
Due to the [changes in python 3.7](https://docs.python.org/3/whatsnew/3.7.html) *async* is now a keyword.

This results in the following Error: 
```
$ python3.7 ChatServer.py localhost:123456
Traceback (most recent call last):
  File "ChatServer.py", line 7, in <module>
    from PodSixNet.Server import Server
  File "/tmp/PodSixNet/examples/PodSixNet/Server.py", line 4
    from PodSixNet.async import poll, asyncore
                       ^
SyntaxError: invalid syntax
```

After the cloning, I moved the *PodSixNet/PodSixNet* directory to *PodSixNet/example/PodSixNet*. With python 2.7 and 3.4 the ChatServer.py runs as expected. But not with 3.7.

Renaming async.py and the imports in Channel.py and Server.py to the non-keyword "notasync" seems to fix this behaviour.

Can somebody verify this error with python 3.7

**Comment by chr15m** [comment]
@CydNoxzed thanks for reporting this & figuring it a fix. Will verify today!

**Comment by chr15m** [comment]
@CydNoxzed I couldn't get python 3.7 installed on my machine but I reproduced the issue using Travis CI (which is set up on this repository now). Will fix, thanks.

**Comment by chr15m** [comment]
@CydNoxzed could you let me know if it's fixed for you on the branch `fix-async`?

**Comment by CydNoxzed** [comment]
@chr15m thanks for the fast reply!

The issue seems to be fixed in the branch fix-async:

`$ python3.7 ChatServer.py localhost:12345
Server launched`

Are you going to push the new PodSixNet version to pypi, after the merge into master?

Thanks again!

**Comment by chr15m** [comment]
Yep I'll merge & release when I'm next at laptop.

I'm surprised it worked as I got errors from Travis regarding asyncore being deprecated in favour of asyncio. That was in 3.7-dev so maybe they un-deprecated it? Or do you have asyncore installed as a module?

**Comment by CydNoxzed** [comment]
Asyncore seems to be a build-in library: https://docs.python.org/3.7/library/asyncore.html
But it's still marked a deprecated.

**Comment by chr15m** [comment]
@CydNoxzed before I merge this I wanted to check whether you are see this errors on the `fix-async` branch?

`AttributeError: 'dispatcher' object has no attribute 'setblocking'`

These are showing up in the Travis build when tested against `3.7-dev`. Maybe they are fixed in `3.7`.

Can you run the unit tests with `python3.7 PodSixNet/test.py` and let me know if you run into this?

https://travis-ci.org/chr15m/PodSixNet/jobs/431508905

```
$ python PodSixNet/test.py
connection
PodSixNet/test.py:96: DeprecationWarning: Please use assertTrue instead.
  self.failUnless(r == self.outgoing.pop(0))
./opt/python/3.7-dev/lib/python3.7/asyncore.py:284: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 31426)>
  sock = socket.socket(family, type)
/opt/python/3.7-dev/lib/python3.7/asyncore.py:284: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 31426), raddr=('127.0.0.1', 53188)>
  sock = socket.socket(family, type)
.ServerTestCase
--------------
E
======================================================================
ERROR: runTest (__main__.ServerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "PodSixNet/test.py", line 154, in setUp
    self.outgoing = EndPointChannel(sender, map=self.server._map)
  File "/home/travis/build/chr15m/PodSixNet/PodSixNet/Channel.py", line 10, in __init__
    asynchat.async_chat.__init__(self, conn, map)
  File "/opt/python/3.7-dev/lib/python3.7/asynchat.py", line 79, in __init__
    asyncore.dispatcher.__init__(self, sock, map)
  File "/opt/python/3.7-dev/lib/python3.7/asyncore.py", line 231, in __init__
    sock.setblocking(0)
AttributeError: 'dispatcher' object has no attribute 'setblocking'
----------------------------------------------------------------------
Ran 3 tests in 0.069s
FAILED (errors=1)
```

By the way instead of copying the PodSixNet directory into examples you can use `pip3 install -e .` and it should set up a development reference to the library. Use `--user` if you don't want to pollute your OS libraries.

**Comment by CydNoxzed** [comment]
I installed PodSixNet now with pip3.7 in a virtualenv. If I run test.py the result is the following: 

```
$ python3.7 test.py 
connection
test.py:96: DeprecationWarning: Please use assertTrue instead.
  self.failUnless(r == self.outgoing.pop(0))
..ServerTestCase
--------------
E
======================================================================
ERROR: runTest (__main__.ServerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 154, in setUp
    self.outgoing = EndPointChannel(sender, map=self.server._map)
  File "/tmp/podsixnet/PodSixNet/PodSixNet/Channel.py", line 10, in __init__
    asynchat.async_chat.__init__(self, conn, map)
  File "/usr/lib64/python3.7/asynchat.py", line 79, in __init__
    asyncore.dispatcher.__init__(self, sock, map)
  File "/usr/lib64/python3.7/asyncore.py", line 231, in __init__
    sock.setblocking(0)
AttributeError: 'dispatcher' object has no attribute 'setblocking'

----------------------------------------------------------------------
Ran 3 tests in 0.063s

FAILED (errors=1)
```

It seems to me that in test.py line 151 it creates an dispatcher object which is going to be used in line 154 to init the EndPointChannel object and from this down to `asyncore.dispatcher` which expect a socket in the given parameter. Could this be the cause?

**Comment by chr15m** [comment]
@CydNoxzed I'm trying to see if this will fix it on line 10 of `Channel.py`:

`asynchat.async_chat.__init__(self, getattr(conn, "socket", conn), map)`

But I have to get 3.7 working first.

**Comment by chr15m** [comment]
Managed to reproduce the bug on python 3.6 and the fix works. Will merge it and publish. Thanks for reporting, suggesting a fix & testing @CydNoxzed! :+1:
