### ISSUE TITLE
Documentation / comments in the code

### ISSUE THREAD

**Issue by source83** [chr15m/PodSixNet#2]
Could you add some comments in the library files to document that's happening and what the variables represent ?  
The __init__ definition in Server.py, does the "listeners=5" statement mean it will not take more than 5 clients connected at a time ?  
I'm using your library (very happily) in a multi player server for JanusVR and it seems it works very well so far, but I do hope you could add some info to some of the files :D

**Comment by chr15m** [comment]
Hello! Better commenting is a good idea, thanks for your feedback.

I haven't touched this code for several years and it's unlikely I will get time to do that but I will certainly merge a pull request that includes better documentation.

I believe `listeners=5` means it will take more than 5 clients but it will only have 5 listeners spawned listening for new connections.

Thanks!

**Comment by source83** [comment]
Okay, so it'll take as many connections as I allow with my code ?
I've heavily modified the library, so I don't think you want my changes in your git repo.  
For one, I've changed the main key from "action" to "method" for it to mesh with the application that connects with it (JanusVR)
I've actually managed to mostly get every thing working as needed, just trying to figure out how to deal with SSL socket wrapping now :( 
Your library was instrumental in getting it done :)

**Comment by chr15m** [comment]
Great! I'm glad it has been helpful. Thanks. :+1:
