### ISSUE TITLE
I try to pass on Bytes data，and get Error

### ISSUE THREAD

**Issue by DexYang** [chr15m/PodSixNet#22]
I try to pass on JPEG Bytes data

and I get this Error

{'action': 'error', 'error': UnicodeDecodeError('utf-8', b'\xff\xd8\xff\xc0\x00\x11\x08\x00\xf.....', 0, 1, 'invalid start byte')}

what should I do

**Comment by chr15m** [comment]
Hello, can you please send a minimal example with the code and image which causes the error?

**Comment by DeluxeYang** [comment]
Client Code：
`
from PodSixNet.Connection import connection
from PodSixNet.Connection import ConnectionListener

class ResourceClient(ConnectionListener):
    def __new__(cls, host, port):
        if not hasattr(cls, '_instance'):
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self, host, port):
        self.Connect((host, port))

    def get_map_unit(self):
        send_data = {
            'action': "get_map_unit"
        }
        self.Send(send_data)

    def Network(self, data):
        print(data)
        # print(data.get("error", 0))

    def Network_receive_map_unit(self, data):
        print(data)


resource_client = ResourceClient( "localhost", int(8002))
resource_client.get_map_unit()
while True:
    connection.Pump()
    resource_client.Pump()
`


Server Code:
`

from time import sleep
from PodSixNet.Channel import Channel
from PodSixNet.Server import Server



class ResourceChannel(Channel):
    def __new__(cls, *args, **kwargs):
        if not hasattr(cls, '_instance'):
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self, *args, **kwargs):
        Channel.__init__(self, *args, **kwargs)
        self.MapX_Pool = {}

    def Network(self, data):
        pass


    def Network_get_map_unit(self, data):
        jpeg = open("p.jpg", "rb")
        send_data = {
            'action': "receive_map_unit",
            'map_id': 0,
            'unit_num': 0,
            'jpg': jpeg.read(),
        }
        self.Send(send_data)



class ResourceServer(Server):
    channelClass  = ResourceChannel

    def __init__(self, *args, **kwargs):
        self.id = 0
        Server.__init__(self, *args, **kwargs)
        print('Server launched')

    def Connected(self, channel, addr):
        print('new connection:', channel)

    def Launch(self):
        while True:
            self.Pump()
            sleep(0.0001)


resource_server = ResourceServer(localaddr=("localhost", int(8002)))
while True:
    resource_server.Launch()
`


Any jpg will does the same

Thank you very much!

**Comment by DeluxeYang** [comment]
Hi, I don't actually understand your code, could you tell me is it repairable?

**Comment by chr15m** [comment]
Yes I think it's repairable. I just need to find time to make a fix (or somebody else can fix it faster).

**Comment by chr15m** [comment]
If I comment out these two lines:

https://github.com/chr15m/PodSixNet/blob/409586d3991599940c3e97e22c0b7c01439ddb3b/PodSixNet/rencode.py#L195-L196

Then your example works and the tests pass. I'm inclined to remove the utf8 conversion stuff although I'm unsure the wider impact, especially in situations where different versions of Python are used on the client and server. Will think about this some more.

**Comment by chr15m** [comment]
A possible better fix for this is to switch to msgpack encoding. It seems like a more robust version of rencode. https://pypi.org/project/msgpack/

**Comment by pauliyobo** [comment]
in alternative, if you fear that the change might have an impact on python 2 users, you could mak a check which will execute that code if the version is not python3.

**Comment by jarodium** [comment]
Hi @chr15m 

If I may give my 2 cents, yes, msgpack would be most welcomed. I am working on connecting a kotlin based tcpclient, which I have already completed talking to podsixnet server, safe for decoding the data from rencode. 
Concerning @pauliyobo's comment, how big of an impact it would have on py2 users? Does still makes sense to support py2?

**Comment by chr15m** [comment]
I don't think it makes sense to support py2 any longer. Nobody is working on this library though so you might want to look at other solutions. I'll merge a PR if somebody sends one.

**Comment by jarodium** [comment]
That is too bad.
Podsixnet is very simple to use. Thank you for your reply :)
