### ISSUE TITLE
connection.Connect() won't work

### ISSUE THREAD

**Issue by GoodClover** [chr15m/PodSixNet#25]
I am new to PodSixNet so if I'm just using it wrong sorry.
(I'm following the Quick Start guide)

When I do connection.connect("127.0.0.1") i get this Error:
`Traceback (most recent call last):
  File "C:\Users\olive\Documents\Python\Pygame Zero\Online Test\client.py", line 21, in <module>
    connection.connect("127.0.0.1")
  File "C:\Users\olive\AppData\Local\Programs\Python\Python37-32\lib\asyncore.py", line 333, in connect
    err = self.socket.connect_ex(address)
AttributeError: 'EndPoint' object has no attribute 'socket'`

I have no Idea what an EndPoint is but it seems whatever the code gives as self is one and it shouldn't be.

**Comment by chr15m** [comment]
Hello @GoodClover.

Thanks for posting your issue.

 * How did you install PodSixNet?
 * Do the scripts in the `examples` folder run for you?
 * Can you supply the source code of the file `C:\Users\olive\Documents\Python\Pygame Zero\Online Test\client.py`?

**Comment by GoodClover** [comment]
Sorry, I thought I'd replied to this apparently I never hit "send"

- I used pip3
- Here's the code: 
  Server: [https://pastebin.com/qYg1YjrU](url)
  Client: [https://pastebin.com/JrBSfaTV](url)
- The examples work, yes.

**Comment by chr15m** [comment]
@GoodClover thank you for the update. I will try to debug this soon.

**Comment by GoodClover** [comment]
Not to be rude, but just bumping this.

**Comment by GoodClover** [comment]
Figured it out: `connection.Connect(("localhost",45454))` should be `connectionListener.Connect(("localhost",45454))`.
But now I get this: `client.py
Username: Goo
You: Banna
Traceback (most recent call last):
  File "C:\Users\olive\Documents\Python\Pygame Zero\Online Test\client.py", line 29, in <module>
    connection.send({"userName":userName, "message":msg})
  File "C:\Users\olive\AppData\Local\Programs\Thonny\lib\asyncore.py", line 360, in send
    result = self.socket.send(data)
TypeError: a bytes-like object is required, not 'dict'`

**Comment by GoodClover** [comment]
Fixed that too, needs a capital S on Send or it calls a different thing,
your quickstart guide is **SERIOUSLY** flawed and needs re-doing.

**Comment by nonoesimposible** [comment]
Part of it isn't the quickstart guide but the actual naming conventions itself. As mentioned in #26, there's a lot of problems that happen with namespace clashing.

**Comment by chr15m** [comment]
@GoodClover I'm glad you got your bug fixed before I was able to look at it.

Thanks for your feedback about the README. Can you let me know a list of problems you see with the documentation so that I can improve it to help people in the future.
