### ISSUE TITLE
Inability to see disconnections

### ISSUE THREAD

**Issue by Amerikranian** [chr15m/PodSixNet#31]
I am unable to see whether someone's connection is dead.
Consider this:
I create a server.
Bob logs in to my server.
Bob kills his game with task manager.
Bob's player is still on the server.
Could you please either
1: Tell me if the library has something to see if a player disconnected or
2: Add in such a feature?
I know a way to get around this -- ping the clients at regular intervals, but that is more work for the server/more packets being sent. Besides, then comes in the question of how often? 1 minute? 3? 15?

**Comment by chr15m** [comment]
Yes the server runs the `Close` method on the channel when the client disconnects. You can see this in the examples:

https://github.com/chr15m/PodSixNet/blob/master/examples/ChatServer.py#L18

Which calls the `DelPlayer` method on the server. You can put your code in there to handle what should happen when a player disconnects.

**Comment by chr15m** [comment]
Note that this will happen when the socket disconnects and under certain conditions the socket may appear from the server perspective to still be alive (the case you mention of a task manager kill may be such a condition). In that situation your proposal to use a heart-beat to see if the connection is alive makes sense. Heartbeats typically have timeouts on the order of 30 seconds to 5 minutes, depending on your application.
