### ISSUE TITLE
[RFC] port codebase to python3

### ISSUE THREAD

**Issue by danobi** [chr15m/PodSixNet#4]
I came across this library a while ago while musing about my new game's architecture. I'd like to use this library, but not in its current state. Therefore, I have put in some considerable effort to revitalize the code base to use python3. However, it came to my attention that `asyncore` (and consequently `asynchat`) are being deprecated [1].

The recommended upgrade path is to use `asyncio`. Unfortunately, `asyncio` uses an explicit async model. This means that if we decide to go the `asyncio` route, games using this library will also have to do `asyncio`-style coroutine programming.

I have no objections to using `asyncio`, but I could see there being some concern. I'd like to hear more thoughts on this.

[1] https://docs.python.org/3.5/library/asyncore.html  (see the note at the top)

**Comment by danobi** [comment]
@chr15m

**Comment by danobi** [comment]
Important to note, if it's not already clear. I'm volunteering to do all the work. I've thought about it a lot, and the work has already begun.

I'm ok if you don't want to upstream my changes, but I thought I'd give it a shot anyways.

**Comment by chr15m** [comment]
Hi @danobi your work sounds very cool!

In terms of Python 3 my preference would be for the fixes required on #1 to be made without changing the architecture fundamentally and while maintaining backwards compatibility with 2.7.

What advantage do you see in porting to asyncio over the current implementation?

**Comment by danobi** [comment]
Hi @chr15m,

I see what you're saying, and I agree that compatibility is good. However, `asyncore` is halfway out the door already [1] [2]. This means we'll experience breaking changes in python >= 3.5 regardless of what we do (short of maintaining our own `asyncore` module). The question is just when. Furthermore, python2.7 is being deprecated in a few years.

I've spent time looking for a more natural upgrade path for `asyncore` and I could only come up with `asyncio`. Here are some advantages and disadvantages I can see with `asyncio`:

# Pros:
- Maintained
- Similar Server / Protocol interfaces to `asyncore` (makes for easy dev work)
- `PodSixNet` will maintain logical compatibility. Meaning you won't have to scratch your head too much to rejigger application logic. Simply call `await asyncio.sleep(.01)` instead of `xxx.Pump()`. That example will be more clear once I have a changeset up.

# Cons
- `asyncio` is confusing [3]
- You'll need to add in an `asyncio` event loop (not as bad as it sounds)
- `PodSixNet` API changes

[1] https://bugs.python.org/issue28533
[2] https://bugs.python.org/issue25002
[3] http://lucumr.pocoo.org/2016/10/30/i-dont-understand-asyncio/

**Comment by chr15m** [comment]
@danobi thanks for investigating this and taking the time to write this up, I really appreciate it.

> short of maintaining our own asyncore module

I wonder what the chances are that somebody will port it to 3 as a module?

In any case, it sounds like you understand the dimensions of this very well and have thought about it thoroughly. Happy to review & merge whatever you come up with given the pros & cons you listed. Thanks!

**Comment by chr15m** [comment]
@danobi there might also be stuff in the python3 branch that you can use: https://github.com/chr15m/PodSixNet/tree/python3

**Comment by selfsame** [comment]
@danobi happy to review & merge a switch to asyncio for the python3 branch, I've fixed it up for python 3.5.2 recently

**Comment by chr15m** [comment]
Cool, thanks @selfsame!

**Comment by Berserker66** [comment]
Any news on this? I remember PodSixNet from years ago and considered using it for a new project, but looking at the commit history and issues this project seems dead, which is a bit unfortunate.

**Comment by selfsame** [comment]
@Berserker66 the python3 branch should be fully functional.  Not sure about the depreciation schedule for asyncore but I'd imagine it'll stick around for quite a few years.

**Comment by Berserker66** [comment]
Well, "should be" turns out to not be.

I downloaded the python 3 package, updated the included rencode, had my ide convert all the tabs to spaces and tried to get the unittest running, which by default it did not because the proper way to do it is:

```
[all the unittest stuff]

if __name__ == "__main__":
    unittest.main()
```

as opposed to

```
if __name__ == "__main__":
    [all the unittest stuff]
    unittest.main()](url)
```

as you can see here: https://docs.python.org/3/library/unittest.html#basic-example

This apparently confused my IDE to run 0 out of 0 tests.
After fixing that up, it ran 1 out of 1 tests, 1 of which error'd.
https://pastebin.com/w1KJQWkJ

**Comment by Berserker66** [comment]
Apparently you'd rather believe I can't check out the correct branch, than to look into it yourself. So here's me looking into it for you as a video:
https://i.imgur.com/uiftJb3.gif
It's broke.

**Comment by selfsame** [comment]
@Berserker66 fair enough. I don't think I've ever ran the unit tests, if you can get them to pass I'd be happy to merge a PR.

The `examples` all seem to working fine `3.6.2` but I guess that doesn't make use of all of PodSixNet

**Comment by chr15m** [comment]
@Berserker66 @selfsame @danobi I've merged the python3 branch. If you run into any bugs feel free to file them.
