### ISSUE TITLE
Wrap async_chat instead of inheriting?

### ISSUE THREAD

**Issue by tdoylend** [chr15m/PodSixNet#6]
Currently, Channel inherits from async_chat. This means it gets the really wonky async_chat.__getattr__ method, which causes [problems like this.](https://groups.google.com/forum/#!topic/podsixnet/KjGcjpSd1Lo)

I propose that instead of inheriting, we make Channel (and also EndPoint, by extension) a wrapper around async_chat. That way, error messages can be more helpful and PodSixNet can move closer to [PEP-8](https://www.python.org/dev/peps/pep-0008/#naming-conventions) by not having capitalized methods.

I'm willing to do this and submit a PR if @chr15m thinks this is a good idea.

**Comment by chr15m** [comment]
Excellent, sounds great, thanks @tdoylend! This could help the Python 3 port as well. Let me know when there is a PR to review.

**Comment by chr15m** [comment]
@tdoylend feel free to re-open this if you submit such a PR. Thanks!
