### ISSUE TITLE
How to change the default port and ip for connection?

### ISSUE THREAD

**Issue by harsh-98** [chr15m/PodSixNet#8]
I making using PodSixNet for client-server scripting in my [game](https://github.com/h4r5h-ja1n/Minecraft-Strike). I have done some changes in the code for making it use different ip and port for the client. #7

**Comment by chr15m** [comment]
Hi @harsh-98 it is already possible to do this as per the documentation:

> connect to the server - optionally pass hostname and port like: ("mccormick.cx", 31425)
> `connection.Connect()`
