### ISSUE TITLE
Pip packaging

### ISSUE THREAD

**Issue by jirislav** [chr15m/PodSixNet#9]
Are you considering maintaning an pip package? It would allow the others to easily add this awesome project as a dependency to their projects.

**Comment by chr15m** [comment]
Good idea. Let me know if this works ok for you: https://pypi.python.org/pypi/PodSixNet/0.8

**Comment by jirislav** [comment]
Yup, that works flawlessly!

Now you can update your Installation part in README to this easier method:

# Installation

```bash
pip install PodSixNet
```

or

```bash
easy_install PodSixNet
```

both should be portable to windows & mac
